#.travis.yml
language: dart

dart:
  - dev
  - stable

dart_task:
  - test
  - dartfmt
  - dartanalyzer

script:
  - pub get --packages-dir
  - pub run test
  - dart --pause-isolates-on-exit --enable-vm-service=9292 test/treasury_direct_test.dart &
  - pub global run coverage:collect_coverage --uri=http://127.0.0.1:9292/ -o coverage.json --resume-isolates
  - bash <(curl -s https://codecov.io/bash) -t a519c310-b26d-49ed-9367-7503bcc9f494 -f coverage.json
