language: dart
sudo: false
dart:
# Install the latest stable release
- stable

dart_task:
  - dart analyze --fatal-warnings --fatal-infos .
  - dart format --set-exit-if-changed .

script:
  - pub global activate coverage
  - pub run test --coverage=lcov.info
  - pub global run coverage:format_coverage --in lcov.info/test/treasury_direct_test.dart.vm.json --out lcov.info --lcov

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.pub-cache
    - .dart_tool/build
