#.travis.yml
language: dart

dart:
  - dev
  - stable

dart_task:
  - test
  - dartfmt
  - dartanalyzer

after_script:
  - pub get
  - pub run test
  - pub global activate coverage
  - dart --pause-isolates-on-exit --enable-vm-service=9292 test/treasury_direct_test.dart &
  - pub global run coverage:collect_coverage --port=9292 -o coverage.json --resume-isolates --connect-timeout=20
  - bash <(curl -s https://codecov.io/bash) -f coverage.json
