name: treasury_direct
version: 0.1.4

description: A Dart library package to access the debt of the United States from the US Treasury Direct site.
author: Larry Aasen <larryaasen@gmail.com>
homepage: https://github.com/larryaasen/treasury_direct

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  async: ^2.3.0
  convert: ^2.1.1
  http: ^0.12.0+2
  intl: ^0.16.0

dev_dependencies:
  test: ^1.9.4
  coverage: ^0.13.3+1
  pedantic: ^1.0.0