name: treasury_direct
version: 2.1.0

description: A Dart library package to access the debt of the United States from the US Treasury Direct site.
homepage: https://github.com/larryaasen/treasury_direct

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  async: ^2.4.0
  convert: ^2.1.1
  http: '>=0.12.2'
  intl: ^0.16.1

dev_dependencies:
  test: ^1.15.3
  coverage: ^0.14.0
  pedantic: ^1.9.2