name: treasury_direct
version: 3.0.1

description: A Dart library package to access the debt of the United States from the US Treasury Direct site.
homepage: https://github.com/larryaasen/treasury_direct

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.8.2
  convert: ^3.0.1
  http: ^0.13.4
  intl: ^0.17.0

dev_dependencies:
  analyzer: ^2.5.0
  coverage: ^1.0.3
  lints: ^1.0.1
  test: ^1.18.2
