name: treasury_direct
version: 3.1.0

description: A Dart library package to access the debt of the United States from the US Treasury Direct site.
homepage: https://github.com/larryaasen/treasury_direct

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  async: '>=2.8.2 <3.0.0'
  convert: '>=3.0.1 < 4.0.0'
  http: '>=0.13.4 < 1.0.0'
  intl: '>=0.17.0 < 1.0.0'

dev_dependencies:
  analyzer: '>=2.5.0 < 7.0.0'
  coverage: '>=1.0.3 <2.0.0'
  lints: '>=2.0.0 <3.0.0'
  test: '>=1.20.0 <2.0.0'
