name: treasury_direct
version: 0.1.0

description: A Dart library package to access the debt of the United States from the US Treasury Direct site.
author: Larry Aasen
homepage: https://github.com/larryaasen/treasury_direct

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  async: ^2.0.8
  convert: ^2.0.2
  http: ^0.12.0
  intl: ^0.15.7

dev_dependencies:
  test: ^1.5.1
